Checking for the version of the python installed and in use in this program

In [ ]:
import sys
if sys.version_info.major==3 and sys.version_info.minor<=8:
    print("Use later version of python")
elif sys.version_info.major==3 and sys.version_info.minor>8:
    print("Hello World")
    print("python version: ",sys.version_info)
    print("python version: ",sys.version)

Hello World
python version:  sys.version_info(major=3, minor=12, micro=12, releaselevel='final', serial=0)
python version:  3.12.12 (main, Oct 10 2025, 08:52:57) [GCC 11.4.0]


## Data types in Python
### Mutable datatypes
these are the data types that can be changed/modified after they have been created. for eg: list. after a list is created we can add to it remove from it and we can also replace elements using append, remove/pop and insert respectively
### Immutable datatypes
these are the datatypes that cannot be changed/modified after they have been created. any operation that seems to modify said datatype will actually just create a new object instead of changing the original object. for eg: tuple

In [ ]:
my_list = [1,2,3,4] #lists are mutable which means we can add and remove from the list. we can also have duplicate values here.
print("original list: ",my_list)
my_list.append(5) #append adds the element to the end of the list
print("New list: ",my_list)
my_list.remove(2) #remove removes the first occurence of the said element from the list. if more than one of the same element only the first one is removed
print("New list: ",my_list)
my_list.insert(1,10) #insert adds the element (10) at index (1) which can be specified
print("New list: ",my_list)
my_list.pop() #this removes the last element of the list.
print("New list: ",my_list)
my_list.pop(2) #we can also specify the index of the element we want to remove using pop. i wrote 2 which will remove the element at index 2 which is 3
print("New list: ",my_list)


original list:  [1, 2, 3, 4]
New list:  [1, 2, 3, 4, 5]
New list:  [1, 3, 4, 5]
New list:  [1, 10, 3, 4, 5]
New list:  [1, 10, 3, 4]
New list:  [1, 10, 4]


In [ ]:
my_tuple = (1,2,3,4)
print("original tuple: ",my_tuple)
# my_tuple.append(5) trying to add to this will raise an error because tuple are immutable
my_tuple = my_tuple + (5,) #we can add to a tuple by concatinating with another tuple. if number is single we need to add comma after it to make it a tuple else it is just a number
print(my_tuple) #if there are multiple numbers we can write in the parenthesis without comma at the end. eg: (5,6,7) but adding the comma will also work so (5,6,7,) will also work


original tuple:  (1, 2, 3, 4)
(1, 2, 3, 4, 5)


## Common   data types in python
### numeric:
1. int: this represents integer values or simply numbers. so 1, 2, 10, 10001, -1000 all are integer values.
2. float: this represents floating type values or decimal numbers. so 1.2, -1.5, 10000.23 all are float values.
3. complex: represents complex values. so 3+4j
### sequence:
these are the data types that are ordered collection of items. here we can access item/element by index
1. string: this is a collection of characters enclosed within double quotes or single quotes. eg: "Hello world". these are immutable.
2. list: this represents a list. so a collection of items in a list which can be of mixed datatypes. these are mutable datatype.
3. tuple: this represents a tuple which are ordered and immutable collection of items. they can also have mixed datatype but are immutable.
### mapping:
this includes data type that store value in key value pair allowing retreival of data based on keys.
1. dictionary: represents dict(dictionary) which can store multi datatype as values with unique keys. these are mutable.
### set:
sets are unordered collection of unique elements. these are useful for membership testing and eleminating duplicate values. these are mutable. but frozenset are immutable versions of set.
### boolean:
this represents the truth value of an element. this can be true of false.
### special:
1. NoneType: represents abscence of value or null value. eg: None
![image.png](attachment:image.png)

In [ ]:
age = 19 #this is int
pi = 3.14 #this is float
temp = -2.9 #this is also float
print("data type of age: ",type(age))
print("data type of pi: ",type(pi))
print("data type of temp: ",type(temp))

data type of age:  <class 'int'>
data type of pi:  <class 'float'>
data type of temp:  <class 'float'>


In [ ]:
name = "Mohak" #this is a string
greet = "Hello"
print("data type of name: ",type(name))
print("data type of greet: ",type(greet))

print("First letter of name:",name[0]) #we can slice and get element of string using the index position of the string.
print("Last letter of name:",name[-1]) #we can also use negative indexing to get the last element of the string. -1 means the last element, -2 means second last and so on.
print("second to fourth letter of name: ",name[1:4]) #we can also slice using range from:to but the to is exclusive so the last index is not included so here only 3 letter is given
print("first three letters of name: ",name[:3]) #if we live first part of range empty it selects the first element by default so it will select 0 index.
print("last three letters of name: ",name[-3:]) #if we leave the last part of range empty it selects the last element by default so it will select -1 index. here we are slicing from -3 to the end of the string so it will give us the last three letters of the string.
print("getting from second letter and : ",name[1:]) #here if we leave the last part empty it will select till last element

data type of name:  <class 'str'>
data type of greet:  <class 'str'>
First letter of name: M
Last letter of name: k
second to fourth letter of name:  oha
first three letters of name:  Moh
last three letters of name:  hak
getting from second letter and :  ohak


In [ ]:
list1 = [1,2,3,4]
print("original list: ",list1)
print("first element of list: ",list1[0]) #getting the first element
print("last element of list: ",list[-1]) #getting the last element using -1
print("second to third element of list: ",list1[1:3]) #we can also use range from:to but again the last value is exclusive
print("out of index? still works: ",list1[1:5]) # if the index is out of range it will not give error but will give till the last element of the list

mixed_list = [1,1.2,"hello",[1,2,3],(4,5),{"name":"Mohak", "age":19}]
print("original mixed list: ",mixed_list)
print("first element of mixed list: ",mixed_list[0]) #getting the first element
print("nested list: ",mixed_list[3])
print("first element of nested list: ",mixed_list[3][0]) #we can also access nested values using this
print("nested tuple: ",mixed_list[4])
print("first element of nested tuple: ",mixed_list[4][0]) #we can also access nested values using this

original list:  [1, 2, 3, 4]
first element of list:  1
last element of list:  list[-1]
second to third element of list:  [2, 3]
out of index? still works:  [2, 3, 4]
original mixed list:  [1, 1.2, 'hello', [1, 2, 3], (4, 5), {'name': 'Mohak', 'age': 19}]
first element of mixed list:  1
nested list:  [1, 2, 3]
first element of nested list:  1
nested tuple:  (4, 5)
first element of nested tuple:  4


In [ ]:
colors = ("red","green","blue","yellow")
print("original colors tuple: ",colors)
print("first color: ",colors[0])
print("last two colors: ",colors[2:])
print("middle color: ",colors[1:3])
colors #we can also print without the print function and it will still give output
# colors[0] = "purple" this gives error as tuple are immutable

original colors tuple:  ('red', 'green', 'blue', 'yellow')
first color:  red
last two colors:  ('blue', 'yellow')
middle color:  ('green', 'blue')


('red', 'green', 'blue', 'yellow')

In [ ]:
person = {"name":"John","age":30,"city":"Pittsburgh"}
print(f"Hello my name is {person["name"]}. I am {person["age"]} years old and I live at {person["city"]}.")
print("All keys:", list(person.keys()))
print("All values:", list(person.values()))

Hello my name is John. I am 30 years old and I live at Pittsburgh.
All keys: ['name', 'age', 'city']
All values: ['John', 30, 'Pittsburgh']


In [ ]:
unique_set = {3,4,5,2,1,1,1,14,5,6,4,3,3,3}
print("original set: ",unique_set) #set does not allow duplicate values so it will only give unique values
#also these are unordered so it will not give in order we have given so it can be randomly ordered.
new_set  = {"a","b","c","d","e","a","a","c","z","x","p","s"}
print("new set: ",new_set) #again only unique values and unordered
#from the output we can see the order is random

original set:  {1, 2, 3, 4, 5, 6, 14}
new set:  {'e', 'z', 'd', 'b', 'x', 'a', 'c', 's', 'p'}


In [ ]:
is_student = True
has_license = False
print("data type of the variable is_student = ",type(is_student))
print("data type of the variable has_license = ",type(has_license))

data type of the variable is_student =  <class 'bool'>
data type of the variable has_license =  <class 'bool'>


In [ ]:
result = None #this is a none type variable which means it does not have any value assigned to it.
print(result) #this will print None

None


In [ ]:
def length_conversion(length, length_type):
    '''
    Converts units of length from meter to feet or feet to meter and returns the converted value to the user.
    Parameters:
    length (float): A floating point value
    length_type (String): A collection of characters used to get the unit type of length (m or ft)
    '''
    if(length_type=="m"):
        length_in_feet = length*3.28084
        return length_in_feet
    elif(length_type=="ft"):
        length_in_meters = length/3.28084
        return length_in_meters
    else:
        return None

def weight_conversion(weight, weight_type):
    """
    Converts units of weight from kg to lbs or lbs to kg and returns the converted value to the user.
    Parameters:
    weight (float): A floating point value
    weight_type (String): A collection of characters used to get the unit type of weight (kg or lbs)
    """
    if(weight_type=="kg"):
        weight_in_pounds = weight*2.20462
        return weight_in_pounds
    elif(weight_type=="lbs"):
        weight_in_kg = weight/2.20462
        return weight_in_kg
    else:
        return None

def volume_conversion(volume, volume_type):
    '''
    Converts units of volume from liters to gallons or gallons to liters and returns the converted value to the user.
    Parameters:
    volume (float): A floating point value
    volume_type (String): A collection of characters used to get the unit type of volume (l or gal)
    '''
    if(volume_type=="l"):
        volume_in_gallons= volume*0.264172
        return volume_in_gallons
    elif(volume_type=="gal"):
        volume_in_liters = volume/0.264172
        return volume_in_liters
    else:
        return None

get_conversion_type = input("Enter the type of conversion you want: length, weight or volume:") #getting the conversion type from the user
try: #its better if i do the .lower() to the get_conversion_type above while taking input to remove repeating the same thing
    if(get_conversion_type.lower()=="length"): #checking if conversion type is length
        length_type = input("Enter unit of length you want to convert from (m or ft): ").strip().lower() #strip to rid of spaces and whitespaces
        length = float(input(f"Enter length in {length_type}: "))
        converted_length = length_conversion(length, length_type) #getting the converted value by passing arguements to function and getting the returned result
        print(f"Converted length: {converted_length:.2f}")
    elif(get_conversion_type.lower()=="weight"): #checking if conversion type is weight
        weight_type = input("Enter unit of weight you want to convert from (kg or lbs): ").strip().lower() #strip to rid of spaces and whitespaces
        weight = float(input(f"Enter weight in {weight_type}: "))
        converted_weight = weight_conversion(weight, weight_type) #getting the converted value by passing arguements to function and getting the returned result
        print(f"Converted weight: {converted_weight:.2f}")
    elif(get_conversion_type.lower()=="volume"): #checking if conversion type is volume
        volume_type = input("Enter unit of volume you want to convert from (l or gal): ").strip().lower() #strip to rid of spaces and whitespaces
        volume = float(input(f"Enter volume in {volume_type}: "))
        converted_volume = volume_conversion(volume, volume_type) #getting the converted value by passing arguements to function and getting the returned result
        print(f"Converted volume: {converted_volume:.2f}")
    else:
        print("Invalid conversion type")
except Exception as e: #error handling for invalid input, type and so on
    print("Error: ",e)


Enter the type of conversion you want: length, weight or volume:length
Enter unit of length you want to convert from (m or ft): m
Enter length in m: 10
Converted length: 32.81


In [ ]:
user_choice = input("choose an operator: sum, avg, max or min: ").strip().lower()
user_input = input("Enter the numbers separated by space: ")

user_input_list = [float(x) for x in user_input.split()]

print(f"your input: {user_input_list}")

def sum_func(lst):
    total = 0
    for i in lst:
        total += i
    return total

def avg_func(lst):
    return sum_func(lst) / len(lst)

def max_func(lst):
    maximum = lst[0]
    for i in lst:
        if i > maximum:
            maximum = i
    return maximum

def min_func(lst):
    minimum = lst[0]
    for i in lst:
        if i < minimum:
            minimum = i
    return minimum

try:
    if user_choice == "sum":
        print(f"sum of list is: {sum_func(user_input_list)}")

    elif user_choice == "avg":
        print(f"avg of list is: {avg_func(user_input_list)}")

    elif user_choice == "max":
        print(f"max of list: {max_func(user_input_list)}")

    elif user_choice == "min":
        print(f"min of list: {min_func(user_input_list)}")

    else:
        print("Invalid Operation")

except Exception as e:
    print("Error:", e)

choose an operator: sum, avg, max or min: sum
Enter the numbers separated by space: 12 34
your input: [12.0, 34.0]
sum of list is: 46.0


In [ ]:
def extract_every_other(lst):
    '''
    this function returns a new list of every other user input elements
    Parameters:
    lst (list): list of elemenents input by the user
    '''
    print(lst)
    new_lst = lst[0:len(lst):2] #can also do lst[::2] so it will take from start to end with 2 step
    return new_lst

user_input = input("Enter the elements of the list separated by space: ")
user_input_list = [float(x) for x in user_input.split()] #we cab split using other things too like .split(",") for comma splitting
# print(user_input_list) testing if the list is cconverted to float point
result = extract_every_other(user_input_list)
print(result)



Enter the elements of the list separated by space: 1 2 4 6 8
[1.0, 2.0, 4.0, 6.0, 8.0]
[1.0, 4.0, 8.0]


In [ ]:
def get_sublist(lst,start,end):
    '''
    this function takes user input for list, start slice and end slice to return a new list of sliced list.
    Parameters:
    lst (list): this is a collectin of elements that is input by the user
    start (int): this is a numeric value input by user for start index of slicing
    end (int): this is a numeric value input by the user for the end index of slicing
    '''
    new_lst = lst[start:end+1] #end+1 because slicing end is exclusive so it does not get included so +1 will make it included
    return new_lst

user_input = input("Enter elements of the list separated by commas: ")
user_input_list = [float(x) for x in user_input.split(",")]
get_start_index = int(input("Enter the start index where to start slicing: "))
get_end_index = int(input("Enter the end index where to end slicing: "))
result = get_sublist(user_input_list,get_start_index,get_end_index)
print(user_input_list)
print(f"{result}")


Enter elements of the list separated by commas: 1,2,5,6,8
Enter the start index where to start slicing: 2
Enter the end index where to end slicing: 4
[1.0, 2.0, 5.0, 6.0, 8.0]
[5.0, 6.0, 8.0]


In [ ]:
def reverse_list(lst):
    '''
    this function returns user input list in a reversed format
    Parameters:
    lst (list): this is a list of items user input
    '''
    return lst[::-1] #so making step -1 makes it go from back to front. so -1 step means move backwards

user_input = input("Enter the list items separated by a space: ")
user_input_list = [float(x) for x in user_input.split()]
result = reverse_list(user_input_list)
print(user_input_list)
print(result)


Enter the list items separated by a space: 12 45 89 65 32
[12.0, 45.0, 89.0, 65.0, 32.0]
[32.0, 65.0, 89.0, 45.0, 12.0]


In [ ]:
def remove_first_last(lst):
    '''
    this function returns user input list and removes the first and last element
    Parameters:
    lst (list): this is a list of items user input
    '''
    return lst[1:-1]   # last element excluded


user_input = input("Enter the list items separated by space: ")
user_input_list = [int(x) for x in user_input.split()]

result = remove_first_last(user_input_list)

print(user_input_list)
print(result)

Enter the list items separated by space: 1 4 6 8 9
[1, 4, 6, 8, 9]
[4, 6, 8]


In [ ]:
def get_first_n(lst,n):
    '''
    this fucntion returns the first n amount of elements of the list the user specifies
    Parameters:
    lst (list): collection of elements input by the user
    n (int): this is a numeric value input by the user
    '''
    return lst[:n] #here no need for +1 as if n=3 it will print the index 0-1-2 which is three elements but if we wanted to get n=3 meaning till index 3 then i would have to do +1

user_input = input("Enter the list items separated by space: ")
user_input_list = [int(x) for x in user_input.split()]
n_elements = int(input("Enter the number of first n elements you want to see: "))
result = get_first_n(user_input_list,n_elements)
print(user_input_list)
print(result)

Enter the list items separated by space: 12 56 78 43
Enter the number of first n elements you want to see: 3
[12, 56, 78, 43]
[12, 56, 78]


In [ ]:
def get_last_n(lst, n):
    '''
    this function returns the n amount of last elements of the list.
    Parameters:
    lst (list): this is a collection of elements input by the user
    n (int): this is a numeric value input by the user
    '''
    return lst[n+1:] #we want the last n number of elements so n+1 will remove n and start from n+1. so n=2 it will start from index 2 which will give 3 elements but +1 will give the last 2 elements

user_input = input("Enter the list items separated by space: ")
user_input_list = [int(x) for x in user_input.split()]
n_elements = int(input("Enter the n amount from last you want to see: "))
result = get_last_n(user_input_list,n_elements)
print(user_input_list)
print(result)

Enter the list items separated by space: 2 4 6 8
Enter the n amount from last you want to see: 2
[2, 4, 6, 8]
[8]


In [ ]:
def reverse_skip(lst):
    '''
    this function returns a reversed list of user input list while skipping every other value
    Parameters:
    lst (list): this is a collection of elements input by the user
    '''
    return lst[::-2]

user_input = input("Enter the items of the list separated by space: ")
user_input_list = [int(x) for x in user_input.split()]
print(user_input_list)
result = reverse_skip(user_input_list)
print(result)

Enter the items of the list separated by space: 2 4 5 7 9
[2, 4, 5, 7, 9]
[9, 5, 2]


In [ ]:
def flatten(lst):
    new_list = []
    for i in lst:
        for j in i:
            new_list.append(j)
    return new_list

nested_list = eval(input("Enter nested list: "))
print(nested_list)
result = flatten(nested_list)
print(result)

Enter nested list: [(1,2), (3,4), (4,5)]
[(1, 2), (3, 4), (4, 5)]
[1, 2, 3, 4, 4, 5]


In [ ]:
def access_nested_element(lst, indices):
    elem=lst
    for i in indices:
        elem=elem[i]
        print(elem) #in the first iteration the elem will be the selected nested list so elem = [4,5,6] if indices[1,n].
        #then in the next iteration the elem = [4,5,6] will be still in use but now the second element of the indices[1,2] the 2 will be in use so it will take the value inside of that list resulting in 6.
        #this is how it will select a nested list and then its item
    return elem

nested_list = eval(input("Enter nested list: "))
print(nested_list)
index = input("Enter indices of list you want to access: ")
index_list = [int(x) for x in index.split()]
result = access_nested_element(nested_list, index_list)
print(result)

Enter nested list: [(2,3), (4,5), (6,7)]
[(2, 3), (4, 5), (6, 7)]
Enter indices of list you want to access: 2
(6, 7)
(6, 7)


In [ ]:
def sum_nested_lst(lst):
    sum=0
    for i in lst:
        for j in i:
            sum+=j
    return sum

nested_list = eval(input("Enter nested list: "))
print(nested_list)
result = sum_nested_lst(nested_list)
print(result)

Enter nested list: [(3,4), (7,8)]
[(3, 4), (7, 8)]
22


In [ ]:
def sum_nested_list(lst):
    total = 0
    for i in lst:
        if isinstance(i, list):   # check if element is a list
            total += sum_nested_list(i)   # recursive call
        else:
            total += i
    return total


nested_list = eval(input("Enter nested list: "))
print(nested_list)

result = sum_nested_list(nested_list)

print("Sum of nested list:", result)

Enter nested list: [[2,3], [5,6]]
[[2, 3], [5, 6]]
Sum of nested list: 16


In [ ]:
def remove_element(lst,elem):
    new_list = []
    for i in lst:
        if isinstance(i,list):
            new_list.append(remove_element(i,elem))
        else:
            if i!=elem:
                new_list.append(i)
    return new_list

nested_list = eval(input("Enter nested list: "))
print(nested_list)
element = int(input("Enter element you want to remove from the list: "))
print("removing element [",element,"] from the list")
result = remove_element(nested_list,element)
print(result)

Enter nested list: [[2,3], [5,6]]
[[2, 3], [5, 6]]
Enter element you want to remove from the list: 3
removing element [ 3 ] from the list
[[2], [5, 6]]


In [ ]:
def find_max(lst):
    # max_num=lst[0] this gives error as list and int comparairiosn
    max_num = float("-inf")
    for i in lst:
        if isinstance(i,list):
            # max_num=find_max(i) this would override the last max number so add a sub max/temp max to check on previous max and new max and then give max to higher number
            sub_max = find_max(i)
            if sub_max>max_num:
                max_num = sub_max
        else:
            if i>max_num:
                max_num=i
    return max_num


nested_list = eval(input("Enter nested list: "))
print(nested_list)
result = find_max(nested_list)
print(result)

Enter nested list: [[2,3], [5,6]]
[[2, 3], [5, 6]]
6


In [ ]:
def count_occurence(lst,elem):
    count=0
    for i in lst:
        if isinstance(i,list):
            count+=count_occurence(i,elem)
        else:
            if(i==elem):
                count+=1
    return count

nested_list = eval(input("Enter nested list: "))
print(nested_list)
element = int(input("Enter the element you want to count for: "))
result = count_occurence(nested_list,element)
print(result)

Enter nested list: [[2,3], [5,6]]
[[2, 3], [5, 6]]
Enter the element you want to count for: 2
1


In [ ]:
def deep_flatten(lst):
    new_list = []
    for i in lst:
        if isinstance(i,list):
            # new_list.append(deep_flatten(i)) here append will add the entire list just as it is to the new list so it wont be a single list but still a nested list
            new_list.extend(deep_flatten(i)) #but extend will extend the new_list with the added list items so it will take the nested list and extend that into the existing list
        else:
            new_list.append(i)
    return new_list

nested_list = eval(input("Enter nested list: "))
print(nested_list)
result = deep_flatten(nested_list)
print(result)

Enter nested list: [[2,3], [5,6]]
[[2, 3], [5, 6]]
[2, 3, 5, 6]


In [ ]:
def sum_count(lst):
    sum=0
    count=0
    for i in lst:
        if isinstance(i,list):
            s,c = sum_count(i)
            sum+=s
            count+=c
        else:
            sum+=i
            count+=1
    return sum, count

def average_nested(lst):
    # sum = sum_count(lst)
    # count = sum_count(lst)
    sum,count = sum_count(lst)
    return sum/count

nested_list = eval(input("Enter nested list: "))
print(nested_list)
result = average_nested(nested_list)
print(result)

Enter nested list: [[2,3], [5,6]]
[[2, 3], [5, 6]]
4.0


In [ ]:
import numpy as np

In [ ]:
zero_arr =  np.zeros((2,3))
print(zero_arr)
zero_arr = np.zeros((2,5),int) #we can also specify the datatype to use
print(zero_arr)
print(zero_arr.shape) #.shape gives the shape of the array. this returns a tuple of the size of the matrix
print(zero_arr.size) #.size gives the total number of elements in the array. returns the no of elements in the array
print(zero_arr.dtype) #.dtype returns the data type of the array elements
print(zero_arr.itemsize) #.itemsize returns the size in byte of one array element. gives size of each element in bytes
print(zero_arr.nbytes) #.nbytes returns the total memory consumed by the array in bytes
print(zero_arr.T) #.T returns the transpose of the matrix
print(zero_arr.flat) #.flat returns an iterator over a 1d representation of the array
for i in zero_arr.flat:
    print(i, end="") #end removes new line and replaces with a empty string so no new line each iteration and also print() by default sets a new line
print()
arr_complex = np.array([1+2j,3+4j])
print(arr_complex.real) #gives real number of complex array
print(arr_complex.imag) #gives imaginary part of number of complex array
print(zero_arr.astype(float)) #.astype(dtype) converts datatype of array elements into specified datatype

[[0. 0. 0.]
 [0. 0. 0.]]
[[0 0 0 0 0]
 [0 0 0 0 0]]
(2, 5)
10
int64
8
80
[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]
0000000000
[1. 3.]
[2. 4.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
zero_dim_arr = np.array(5)
print(zero_dim_arr)
# one_dim_arr = np.array(1,2,3) error
one_dim_arr = np.array([1,2,4])
print(one_dim_arr)
n_dim_arr = np.array([[1,2,3],[1,5,6],[5,6,10]])
print(n_dim_arr)
print(n_dim_arr.ndim) #.ndim gives the dimension of the array
print(n_dim_arr.dtype) #.dtype gives the datatype of the array
three_d_array = np.array([[[1,2],[3,4]],[[1,2],[2,4]]])
print(three_d_array)

5
[1 2 4]
[[ 1  2  3]
 [ 1  5  6]
 [ 5  6 10]]
2
int64
[[[1 2]
  [3 4]]

 [[1 2]
  [2 4]]]


In [ ]:
list_item = [[1,2,3],[4,5,6]]
# print(list_item.shape) gives error
arr = np.array(list_item)
print(arr)
print(arr.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [ ]:
arr = np.array([1,2,3])
# print(arr.shape[1]) index out of range error
print(arr.shape)
print(arr.shape[0])
if len(arr.shape)>1: #like error handling we are doing here
    print(arr.shape[1])

(3,)
3


In [ ]:
arr  = np.array([[1,2,4],[5,6,7]])
# print(arr.shape()) type error cause .shape is attribute and not a function
print(arr.shape)
if len(arr.shape)>1:
    print(arr.shape[1])

(2, 3)
3


In [ ]:
a = np.array([[1,2],[3,4]])
b = np.array([1,2,3])
# c=a+b value error cause shapes do not match

In [ ]:
# large_arr = np.ones((10000000,100000000)) memory error as the array is too large
arr = np.ones((2,2)) #.ones gives array of 1
print(arr)

[[1. 1.]
 [1. 1.]]


In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
reshaped_arr = arr.reshape(3,2) #this reshapes the array row,column
print(reshaped_arr)
# reshaped_arr = arr.reshape(4,2) this gives value error because the shape does not match
reshaped_arr = arr.reshape(1,6)
print(reshaped_arr)
reshaped_arr = arr.reshape(6,1)
print(reshaped_arr)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
[[1 2 3 4 5 6]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [ ]:
a = np.arange(1,10,2,float) #this makes a array with evenly spaced values.
# np.arange(start, stop,step,dtype)
print(a)

x = range(1,10,2) #sets x as range from start to stop. range(start,stop,step)
print(x)
print(list(x)) #converting x to list to print the list values

x = np.arange(10.4) #makes array with evenly shaped values. here 1 val means the stop value and start will be from 0
print(x)
x=np.arange(0.5,10.4,0.8)
print(x)

print(np.linspace(1,10)) #linespace(start,stop,num=,endpoint,retstep)
print(np.linspace(1,10,7,endpoint=False))
print(np.linspace(1,10,7,endpoint=True))
print(np.linspace(1,10,7))


[1. 3. 5. 7. 9.]
range(1, 10, 2)
[1, 3, 5, 7, 9]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 0.5  1.3  2.1  2.9  3.7  4.5  5.3  6.1  6.9  7.7  8.5  9.3 10.1]
[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]
[1.         2.28571429 3.57142857 4.85714286 6.14285714 7.42857143
 8.71428571]
[ 1.   2.5  4.   5.5  7.   8.5 10. ]
[ 1.   2.5  4.   5.5  7.   8.5 10. ]


In [ ]:
arr = np.empty((2,2)) #we can also specify datatype like .empty((2,2),float)
print(arr)

# arr = np.eye((3,3)) type error
arr = np.eye(3) #cannot specify datatype here. identity matrix are square so no need for shape to be specified
print(arr)

[[4.9e-324 9.9e-324]
 [1.5e-323 2.0e-323]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
arr1 = np.array([[1,2],[2,3]])
arr2 = np.array([[5, 6], [7, 8]])
hstacked = np.hstack((arr1,arr2))
print(hstacked)
vstacked = np.vstack((arr1,arr2))
print(vstacked)
colstacked = np.column_stack((arr1,arr2))
print(colstacked)
colstacked = np.vstack((arr1[0],arr2[1]))
print(colstacked)
colstacked = np.hstack((arr1[0],arr2[1]))
print(colstacked)
colstacked = np.column_stack((arr1[0],arr2[1]))
print(colstacked)

[[1 2 5 6]
 [2 3 7 8]]
[[1 2]
 [2 3]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [2 3 7 8]]
[[1 2]
 [7 8]]
[1 2 7 8]
[[1 7]
 [2 8]]


In [ ]:
# Creating two 3D arrays
arr1 = np.array([[[1], [2]], [[3], [4]]]) # Shape: (2, 2, 1)
arr2 = np.array([[[5], [6]], [[7], [8]]]) # Shape: (2, 2, 1)
# Concatenate along axis 0 (vertical stacking)
concat_axis0 = np.concatenate((arr1, arr2), axis=0)
# Shape of concat_axis0: (4, 2, 1), arr1 is stacked on top of arr2
# Concatenate along axis 1 (horizontal stacking)
concat_axis1 = np.concatenate((arr1, arr2), axis=1)
# Shape of concat_axis1: (2, 4, 1), arr1 and arr2 are placed side by side
# Concatenate along axis 2 (depth stacking)
concat_axis2 = np.concatenate((arr1, arr2), axis=2)
# Shape of concat_axis2: (2, 2, 2), arr1 and arr2 are stacked in depth (third
# dimension)
# Displaying the results
print("Concatenation along axis 0 (Vertical stacking):\n", concat_axis0)
print("Shape of concatenated array along axis 0:", concat_axis0.shape)
print("\nConcatenation along axis 1 (Horizontal stacking):\n", concat_axis1)
print("Shape of concatenated array along axis 1:", concat_axis1.shape)
print("\nConcatenation along axis 2 (Depth stacking):\n", concat_axis2)
print("Shape of concatenated array along axis 2:", concat_axis2.shape)

Concatenation along axis 0 (Vertical stacking):
 [[[1]
  [2]]

 [[3]
  [4]]

 [[5]
  [6]]

 [[7]
  [8]]]
Shape of concatenated array along axis 0: (4, 2, 1)

Concatenation along axis 1 (Horizontal stacking):
 [[[1]
  [2]
  [5]
  [6]]

 [[3]
  [4]
  [7]
  [8]]]
Shape of concatenated array along axis 1: (2, 4, 1)

Concatenation along axis 2 (Depth stacking):
 [[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]
Shape of concatenated array along axis 2: (2, 2, 2)


In [ ]:
#universal functions

arr = np.array([1,2,3,4])
print(arr)
squared = np.square(arr)
print(squared)
sqrt = np.sqrt(arr)
print(sqrt)

[1 2 3 4]
[ 1  4  9 16]
[1.         1.41421356 1.73205081 2.        ]


In [ ]:
a = np.array([[1,2],[3,4]])
b = np.array([[5, 6], [7, 8]])
product = np.dot(a,b)
print(product)

# print(np.det(a))
print(np.linalg.det(a))
print(np.linalg.inv(b))
print()

eigvals, eigvecs = np.linalg.eig(a)
print(eigvals)
print(eigvecs)

[[19 22]
 [43 50]]
-2.0000000000000004
[[-4.   3. ]
 [ 3.5 -2.5]]

[-0.37228132  5.37228132]
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [ ]:
A = np.array([[1], [2], [3]]) # Shape (3,1) 3 rows, 1 column
B = np.array([10, 20, 30]) # Shape (3,) 1D array (3 elements)
C = A + B # Works! Result shape: (3,3)
print(C)

# this wont allow broadcasting with the shape and the two dimensions are not equal
a = np.array([[1,2],[3,4]])
b = np.array([1,2,3])
# c = a+b
# print(c)

[[11 21 31]
 [12 22 32]
 [13 23 33]]


## Vectorization
converting an operation that uses loops into operation that uses Numpy array operations which optimizes performance. these are much faster than loop based equivalents.
### why vectorization
1. efficient = eliminates need of loop as numpy performs computation internally in compiled code
2. readability = code becomes more conside and easier to understand
3. memory efficiency = vectorized operations do not require creation of additional arrays as they work in place

this speeds up math operations by eliminating explicit loops and leverages optimized array computations.

In [ ]:
import time

size = 10**6 #** means power
a = np.random.rand(size)
b = np.random.rand(size)

start_time = time.time()
result_loop = np.zeros(size)
for i in range(size):
    result_loop[i] = a[i]+b[i]
end_time = time.time()
loop_time = end_time - start_time
print(f"loop execution time: {loop_time:.5f} seconds")


# using numpys vectorization
start_time = time.time()
result_vectorized = a+b
end_time = time.time()
vectorized_time = end_time - start_time
print(f"Vectorized time: {vectorized_time:.5f} seconds")
speedup = loop_time/vectorized_time
print(f"vectorization is approximately {speedup:.2f} times faster")

loop execution time: 0.46250 seconds
Vectorized time: 0.00485 seconds
vectorization is approximately 95.40 times faster


In [ ]:
empty_arr = np.empty((2,2))
print(empty_arr)
one_arr = np.ones((4,2),int)
print(one_arr)
new_arr = np.full(one_arr.shape,int)
print(new_arr)
new_zero_arr = np.zeros_like(new_arr)
print(new_zero_arr)
new_ones_arr = np.ones_like(new_arr,int)
print(new_ones_arr)
new_list = [1,2,3,4]
print(np.array(new_list))
print(type(np.array(new_list)))

[[4.9e-324 9.9e-324]
 [1.5e-323 2.0e-323]]
[[1 1]
 [1 1]
 [1 1]
 [1 1]]
[[<class 'int'> <class 'int'>]
 [<class 'int'> <class 'int'>]
 [<class 'int'> <class 'int'>]
 [<class 'int'> <class 'int'>]]
[[0 0]
 [0 0]
 [0 0]
 [0 0]]
[[1 1]
 [1 1]
 [1 1]
 [1 1]]
[1 2 3 4]
<class 'numpy.ndarray'>


In [ ]:
arr = np.arange(10,49)
print(arr)

arr = np.arange(0,9).reshape(3,3)
print(arr)

arr = np.eye(3)
print(arr)

size=30
arr = np.random.random(size)
print(arr)
mean_arr = arr.mean()
print(mean_arr)

arr = np.random.random(100).reshape(10,10)
print(arr)
min = arr.min() #we can also use np.min(arr) and np.max(arr) for numpy
max = arr.max()
print(min,max)



[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[0.70154701 0.71727017 0.23607908 0.94738694 0.91861091 0.33740675
 0.79388861 0.64404815 0.39453266 0.8069458  0.49919847 0.57958799
 0.30308462 0.30547067 0.78254853 0.40123235 0.18631108 0.91219908
 0.6401329  0.86625865 0.30167208 0.68551239 0.5346712  0.16225531
 0.41500436 0.11534084 0.16787954 0.29368372 0.70014008 0.4964227 ]
0.528210754920218
[[0.56485888 0.46670046 0.47039043 0.90122335 0.81106091 0.93512869
  0.60762489 0.83687528 0.83627832 0.3842227 ]
 [0.56983134 0.48102315 0.79113571 0.12724278 0.91542774 0.72035376
  0.14928882 0.40599257 0.0761731  0.54569262]
 [0.14106435 0.22742952 0.10682518 0.27958354 0.7662773  0.22060341
  0.80392882 0.97640396 0.6206188  0.01015583]
 [0.69559847 0.9396756  0.12503721 0.25683733 0.07601749 0.1540251
  0.47469686 0.91309312 0.24598404 0.26645142]
 [

In [ ]:
arr = np.zeros((2,5))
print(arr.size)
print(arr)
arr[0,4] = 1
# we can also do arr[0][4] = 1
print(arr)

10
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]]


In [ ]:
arr = [1,2,0,0,4,0]
reversed_arr = np.flip(arr)
print(reversed_arr)
rev_arr = arr[::-1]
print(rev_arr)

[0 4 0 0 2 1]
[0, 4, 0, 0, 2, 1]


In [ ]:
arr = np.zeros((5,5),int)
arr[0,:]=1 #[start row,column:end]
arr[-1,:] = 1
arr[:,0] = 1
arr[:,-1] = 1
print(arr)


[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [ ]:
arr = np.zeros((8,8),int)
arr[::2,1::2] = 1 #start:stop:step
arr[1::2, 0::2] = 1
print(arr)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [ ]:
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

add_1 = x+y
sub_1 = y-x
print(add_1)
print(sub_1)

add_2 = v+w
sub_2 = w-v
print(add_2)
print(sub_2)

mult_1 = 2*x
print(mult_1)

square = np.square(v)
print(square)

dot_product =  np.dot(v,w)
print(dot_product)
dot_product = np.dot(x,v)
print(dot_product)
dot_product = np.dot(v,w)
print(dot_product)

print(np.vstack((x,y))) #row
print(np.hstack((v,w))) #column
# print(np.concatenate((x,v),axis=0)) #so thos gives value error: all inputs need to have same dimension but x is 2d and v is 1d

[[ 6  8]
 [10 13]]
[[4 4]
 [4 3]]
[20 22]
[2 2]
[[ 2  4]
 [ 6 10]]
[ 81 100]
219
[29 77]
219
[[1 2]
 [3 5]
 [5 6]
 [7 8]]
[ 9 10 11 12]


In [ ]:
import numpy as np

a = np.array([[3,4],[7,8]])
b = np.array([[5,3],[2,1]])

inv_a = np.linalg.inv(a)

dot_product = np.dot(a, inv_a)

id_matrix = np.eye(a.shape[0])

print(dot_product)
print(id_matrix)

print(np.allclose(dot_product, id_matrix))  # handles floating point error

[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
[[1. 0.]
 [0. 1.]]
True


In [ ]:
a = np.array([[3,4],[7,8]])
b = np.array([[5,3],[2,1]])

axb = a @ b #same as np.dot(a,b)
bxa = b @ a

print(np.allclose(axb,bxa))

False


In [ ]:
a = np.array([[3,4],[7,8]])
b = np.array([[5,3],[2,1]])

ab = a@b
abt = ab.T
at = a.T
bt = b.T
atbt = at@bt
print(np.allclose(abt,atbt)) #this is false cause abT = bTaT but we are doing aTbT which is wrong
btat = bt@at
print(np.allclose(abt,btat)) #this is true cause following correct rule

False
True


In [ ]:
a = np.array([[2,-3,1],[1,-1,2],[3,1,-1]])
b = np.array([-1,-3,9])
a_inv = np.linalg.inv(a)
x = a_inv@b
print(f"solution for [x,y,z] = {x}")

solution for [x,y,z] = [ 2.  1. -2.]


In [ ]:
#Element-wise Addition

size = 1000000

#Python lists
list1 = list(range(size))
list2 = list(range(size))
list_add = []

start = time.time()
for i in range(size):
    list_add.append(list1[i] + list2[i])
end = time.time()
print("Python list addition time:", end - start, "seconds")

#numpy arrays
arr1 = np.array(list1)
arr2 = np.array(list2)

start = time.time()
arr_add = arr1 + arr2
end = time.time()
print("NumPy array addition time:", end - start, "seconds")

#element wise multiplication

#python lists
list_mul = []
start = time.time()
for i in range(size):
    list_mul.append(list1[i] * list2[i])
end = time.time()
print("Python list multiplication time:", end - start, "seconds")

#numpy arrays
start = time.time()
arr_mul = arr1 * arr2
end = time.time()
print("NumPy array multiplication time:", end - start, "seconds")

# dot product
# Python lists
dot_list = 0
start = time.time()
for i in range(size):
    dot_list += list1[i] * list2[i]
end = time.time()
print("Python list dot product time:", end - start, "seconds")

# numpy arrays
start = time.time()
dot_arr = np.dot(arr1, arr2)
end = time.time()
print("NumPy array dot product time:", end - start, "seconds")

# matrix mult
matrix_size = 1000

# Python lists
py_mat1 = [[i for i in range(matrix_size)] for _ in range(matrix_size)]
py_mat2 = [[i for i in range(matrix_size)] for _ in range(matrix_size)]
py_result = [[0]*matrix_size for _ in range(matrix_size)]

start = time.time()
for i in range(matrix_size):
    for j in range(matrix_size):
        for k in range(matrix_size):
            py_result[i][j] += py_mat1[i][k] * py_mat2[k][j]
end = time.time()
print("Python lists matrix multiplication time:", end - start, "seconds")

# numpy arrays
np_mat1 = np.array(py_mat1)
np_mat2 = np.array(py_mat2)

start = time.time()
np_result = np_mat1 @ np_mat2
end = time.time()
print("NumPy arrays matrix multiplication time:", end - start, "seconds")

Python list addition time: 0.15685343742370605 seconds
NumPy array addition time: 0.002135038375854492 seconds
Python list multiplication time: 0.16435551643371582 seconds
NumPy array multiplication time: 0.0030710697174072266 seconds
Python list dot product time: 0.20049524307250977 seconds
NumPy array dot product time: 0.0019693374633789062 seconds
Python lists matrix multiplication time: 349.2600383758545 seconds
NumPy arrays matrix multiplication time: 2.573402166366577 seconds
